#!/usr/bin/env ruby

puts "+ Loading environment..."
require 'config/environment'

[Artist, Album, Track].each { |table| table.truncate! }

for source in Source.all
  puts "+ Importing albums..."
  source.import!
  
  puts "#{source.albums.count} albums imported"
end


