#!/usr/bin/env ruby
puts "+ Loading environment..."
require 'config/environment'

for source in Source.all
  puts "#{source}"
  puts "+ Removing old albums..."
  source.clear!
  
  puts "+ Importing albums..."
  source.import!
  
  puts "#{source.albums.count} albums imported"
end


