# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define(:version => 18) do

  create_table "albums", :force => true do |t|
    t.column "name",         :string
    t.column "artist_id",    :integer
    t.column "year",         :integer
    t.column "tracks_count", :integer
    t.column "compilation",  :boolean
    t.column "updated_at",   :datetime
    t.column "created_at",   :datetime
  end

  add_index "albums", ["artist_id"], :name => "index_albums_on_artist_id"
  add_index "albums", ["name"], :name => "index_albums_on_name"
  add_index "albums", ["updated_at"], :name => "index_albums_on_updated_at"

  create_table "artists", :force => true do |t|
    t.column "name",         :string
    t.column "albums_count", :integer
    t.column "tracks_count", :integer
    t.column "updated_at",   :datetime
    t.column "created_at",   :datetime
  end

  add_index "artists", ["name"], :name => "index_artists_on_name"
  add_index "artists", ["updated_at"], :name => "index_artists_on_updated_at"

  create_table "login_histories", :force => true do |t|
    t.column "user_id",     :integer
    t.column "created_at",  :datetime
    t.column "ip",          :string
    t.column "hostname",    :string
    t.column "system_info", :string
  end

  add_index "login_histories", ["user_id"], :name => "index_login_histories_on_user_id"

  create_table "playlists", :force => true do |t|
    t.column "name",    :string
    t.column "user_id", :integer
  end

  add_index "playlists", ["user_id"], :name => "index_playlists_on_user_id"

  create_table "playlists_tracks", :id => false, :force => true do |t|
    t.column "playlist_id", :integer
    t.column "track_id",    :integer
  end

  add_index "playlists_tracks", ["track_id"], :name => "index_playlists_tracks_on_track_id"
  add_index "playlists_tracks", ["playlist_id"], :name => "index_playlists_tracks_on_playlist_id"

  create_table "sessions", :force => true do |t|
    t.column "session_id", :string
    t.column "data",       :text
    t.column "updated_at", :datetime
    t.column "created_at", :datetime
  end

  add_index "sessions", ["session_id"], :name => "index_sessions_on_session_id"
  add_index "sessions", ["updated_at"], :name => "index_sessions_on_updated_at"

  create_table "similar_artists", :force => true do |t|
    t.column "artist_id",     :integer
    t.column "similar_cache", :text
    t.column "updated_at",    :datetime
  end

  add_index "similar_artists", ["artist_id"], :name => "index_similar_artists_on_artist_id"

  create_table "sources", :force => true do |t|
    t.column "name",        :string
    t.column "description", :string
    t.column "uri",         :string
    t.column "encoding",    :string
  end

  create_table "tracks", :force => true do |t|
    t.column "title",         :string
    t.column "album_id",      :integer
    t.column "number",        :string,   :limit => 10
    t.column "disc",          :integer
    t.column "artist_id",     :integer
    t.column "relative_path", :string
    t.column "filename",      :string
    t.column "source_id",     :integer
    t.column "length",        :float
    t.column "bitrate",       :integer
    t.column "vbr",           :boolean
    t.column "updated_at",    :datetime
    t.column "created_at",    :datetime
    t.column "bytes",         :integer
    t.column "ctime",         :datetime
    t.column "mtime",         :datetime
  end

  add_index "tracks", ["title"], :name => "index_tracks_on_title"
  add_index "tracks", ["album_id"], :name => "index_tracks_on_album_id"
  add_index "tracks", ["number"], :name => "index_tracks_on_number"
  add_index "tracks", ["relative_path"], :name => "index_tracks_on_relative_path"
  add_index "tracks", ["filename"], :name => "index_tracks_on_filename"
  add_index "tracks", ["source_id"], :name => "index_tracks_on_source_id"
  add_index "tracks", ["updated_at"], :name => "index_tracks_on_updated_at"

  create_table "users", :force => true do |t|
    t.column "name",       :string
    t.column "password",   :string
    t.column "fullname",   :string
    t.column "email",      :string
    t.column "created_at", :string
    t.column "validated",  :boolean, :default => false
    t.column "upload_dir", :string
  end

  add_index "users", ["name"], :name => "index_users_on_name"

end
